<?php $id = $this->getRequest()->getParam('order_id'); ?>


<?php $delivery = Mage::getModel('delivery/deliverydate')->load($id, 'order_id');
?>
<?php $_order = $this->getOrder() ?>
<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<div class="col2-set">
    <?php if (!$_order->getIsVirtual()): ?>
        <div class="col-1">
            <h2><?php echo $this->__('Shipping Address') ?></h2>
            <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
        </div>

        <div class="col-2">
        <?php else: ?>
            <div class="col-1">
            <?php endif; ?>
            <h2><?php echo $this->__('Billing Address') ?></h2>
            <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
        <?php if (!$_order->getIsVirtual()): ?>
        </div>
       </div>
        <div class="col2-set">
            <div class="col-1">
                <h2><?php echo $this->__('Shipping Method') ?></h2>
                <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
            </div>
        <?php endif; ?>
        <div class="col-2">
            <h2><?php echo $this->__('Payment Method') ?></h2>
            <?php echo $this->getPaymentInfoHtml() ?>
        </div>
    </div>
    <div class="col2-set">
      
            <div class="box">
                <div class="">
                    <h2><?php echo $this->__('Expected Delivery Date') ?></h2>  
                </div> 
                <div>
                    <?php
                    $date_format = Mage::getStoreConfig('delivery/general/delivery_format');

                    if ($date_format == '')
                        $date_format = 'd/M/Y';
                    else
                        $date_format.=" ";
                    if ($delivery->getData('delivery_date') != '') {
                        echo $this->__("Delivery Date :") . $currentDate = date($date_format, strtotime($delivery->getData('delivery_date')));
                    }
                    ?>
                </div>
                <div>
                    <?php
                    if ($delivery->getData('hourstart') != '')
                        echo $this->__("Delivery Time :" . $delivery->getData('hourstart'));
                    ?>
                </div>
                <div>
                    <?php
                    if ($delivery->getData('description') != '') {
                        echo $this->__("Delivery Comment :" . $delivery->getData('description'));
                    }
                    ?>
                </div>
            </div>
        
    </div>

    <h2><?php echo $this->__('Items Ordered') ?></h2>
    <table class="data-table" id="my-orders-table">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th><?php echo $this->__('SKU') ?></th>
                <th class="a-right"><?php echo $this->__('Price') ?></th>
                <th class="a-center"><?php echo $this->__('Qty') ?></th>
                <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
            </tr>
        </thead>
        <tfoot>
            <?php echo $this->getChildHtml('order_totals') ?>
        </tfoot>
        <?php $_items = $_order->getItemsCollection(); ?>
        <?php $_count = $_items->count(); ?>
        <?php foreach ($_items as $_item): ?>
            <?php if ($_item->getParentItem()) continue; ?>
            <tbody>
                <?php echo $this->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table', {'tbody': ['odd', 'even'], 'tbody tr': ['first', 'last']})</script>
    <script type="text/javascript">window.print();</script>
