<?php $captcha = Mage::helper('recaptcha'); ?>
<?php if ($captcha->isEnabled()) : ?>
    <script type="text/javascript">
        window.formToProtectOnPage = [];
        var currentFormId = id = '';
        formsToProtect = <?= $captcha->getSelectorsJson() ?>;
        formsToProtect.forEach(function(item) {
            formToProtect = jQuery(item)[0];
            if (formToProtect) {
                window.formToProtectOnPage.push(formToProtect);
            }
        });
        setTimeout(function(){ 
            if (window.formToProtectOnPage.length) {
                var recaptchaScript = document.createElement('script');
                recaptchaScript.src = 'https://www.google.com/recaptcha/api.js?onload=mtInvisibleCaptchaOnloadCallback&render=<?php echo $captcha->getSiteKey(); ?>';
                recaptchaScript.attributes = 'async defer';
                document.body.appendChild(recaptchaScript);
            }

            window.mtInvisibleCaptchaOnloadCallback = function () {
                for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                    window.formToProtectOnPage[i].innerHTML +=
                        '<input class="invisible_token" type="hidden" name="invisible_token" value=""/>';
                }

                for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                    var form = window.formToProtectOnPage[i];
                    if (form.tagName.toLowerCase() != 'form') {
                        continue;
                    }
                    currentFormId = form.id;
                    currentFormId = currentFormId.replace(/\W+(?!$)/g, '');
                    grecaptcha.ready(function() {
                        grecaptcha.execute('<?php echo $captcha->getSiteKey(); ?>', {action: currentFormId})
                            .then(function(token) {
                                jQuery(".invisible_token").val(token);
                            });
                    });
                }
            };

        }, 3000);
        
    </script>
<?php endif; ?>