<?php 
$write = Mage::getSingleton('core/resource')->getConnection('core_write');
$pakadooId = '';
if(Mage::getSingleton('customer/session')->isLoggedIn()) {
	$customerData = Mage::getSingleton('customer/session')->getCustomer();
	$customerId = $customerData->getId();

	$write = Mage::getSingleton('core/resource')->getConnection('core_write');
    $prefix = (string) Mage::getConfig()->getTablePrefix();
	$querry = "SELECT * FROM `".$prefix."pakadoo` WHERE `customer_id` = '".$customerId."'";
	$pakadooCollection = $write->fetchAll($querry);

	if(!empty($pakadooCollection) && isset($pakadooCollection[0]['pakadoo_id'])){
		$pakadooId = $pakadooCollection[0]['pakadoo_id'];
	}
}
?>

<?php if (trim($pakadooId) == ''):?>
	<?php if ($this->isPossibleOnepageCheckout()):?>
		<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Proceed to Checkout')) ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="linkToCkeckoutPakadoo('<?php echo $this->getCheckoutUrl() ?>');"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
	<?php endif?>
<?php else: ?>
	<?php if ($this->isPossibleOnepageCheckout()):?>
		<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Proceed to Checkout')) ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $this->getCheckoutUrl() ?>';"><span><span><?php echo $this->__('Proceed to Checkout') ?></span></span></button>
	<?php endif?>
<?php endif?>

