<?php
$pakadooId = '';
if(Mage::getStoreConfig('shipcloud/sp_pakadoo_with_shipcloud/pakadoo_with_shipcloud_select',Mage::app()->getStore()->getId())):
		if(Mage::getSingleton('customer/session')->isLoggedIn()) {
			$customerData = Mage::getSingleton('customer/session')->getCustomer();
			$customerId = $customerData->getId();

			$write = Mage::getSingleton('core/resource')->getConnection('core_write');
            $prefix = (string) Mage::getConfig()->getTablePrefix();
			$querry = "SELECT * FROM `".$prefix."pakadoo` WHERE `customer_id` = '".$customerId."'";
			$pakadooCollection = $write->fetchAll($querry);

			if(!empty($pakadooCollection) && isset($pakadooCollection[0]['pakadoo_id'])){
				$pakadooId = $pakadooCollection[0]['pakadoo_id'];
			}
		}

		$sessionPakadooId = Mage::getSingleton('core/session')->getPakadooId();
		if(is_null($sessionPakadooId) || empty($sessionPakadooId) || trim($sessionPakadooId) == ''){
			$sessionPakadooId = '';
		}
		?>

		<?php if (trim($pakadooId) == ''):?>
		<div>
			<label for="cartPakadooId"><?php echo $this->__('PAKADOO ID') ?></label>
			<input id="cartPakadooId" name="cartPakadooId" type="text" size="10" value="<?php echo $sessionPakadooId; ?>">
		</div>
		<div>
			<span>You didn't know what "pakadoo"is? Feel free and visit
				<a href="http://www.pakadoo.de/" title="pakadoo.de" target="_blank" >
					http://www.pakadoo.de
				</a>
			</span>
		</div>

		<script type="text/javascript">
		function linkToCkeckoutPakadoo(checkoutUrl) {

			var pakadooId = document.getElementById('cartPakadooId').value;

			var xhr = new XMLHttpRequest();

			var params = '?cartPakadooId=' + pakadooId;
			var url = "<?php echo $this->getUrl('shipcloud/session/session/') ?>";

			xhr.open("GET", url + params, true);

			xhr.onreadystatechange = function() {//Call a function when the state changes.
				if(xhr.readyState == 4 && xhr.status == 200) {
					window.location = xhr.responseText;
				}
			}

			xhr.send();
		}
		</script>
		<?php endif;?>
<?php endif;?>
