<script type="text/javascript">
    //<![CDATA[
    function sendPickupRequest() {

	var e = document.getElementById("shipcloud_sp_pickup_manualy_pickup_manualy_carrier");
	var valueCarrier = e.options[e.selectedIndex].value;

	var valuePickupDate = document.getElementById("shipcloud_sp_pickup_manualy_pickup_manualy_date").value;
	valuePickupDate = valuePickupDate.replace("/", "-");
	valuePickupDate = valuePickupDate.replace("/", "-");

	var url = '<?php echo $this->getAjaxCheckUrl() ?>'+'carrier/'+valueCarrier+'/pickup_date/'+valuePickupDate

        new Ajax.Request(url, {
            method:     'get',
            onSuccess: function(transport){
 		window.location.reload();
				/*if (transport.responseText){
					alert('Checked')
				}*/
            }
        });
    }
    //]]>
</script> 
<?php echo $this->getButtonHtml() ?>
