<?php

/**
 * @author  Marcell Stork <info@stork.es>
 * @copyright (c) 2013 Stork Business Service Ltd. (http://www.stork.es)
 * @package Stork_Shipcloud
 * @category Shipping
 */

?>

<?php $_shipment=$this->getShipment() ?>

<?php $_order=$this->getOrder() ?>

<?php

	$rplChars = array(" " => '');

	$string = "";

	if ($this->getOrder()) {

		$string = $this->getOrder()->getShippingAddress()->getPostcode();

	}

	$zipcode = strtr($string,$rplChars);?>



<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>

<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">

    <thead>

        <tr>

            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo $this->__('Shipped By') ?></th>

            <th align="center" bgcolor="#d9e5ee" style="padding:3px 9px"><?php echo $this->__('Tracking Number') ?></th>

        </tr>

    </thead>

    <tbody>
			<?php
				$shipcloud = Mage::getModel('shipcloud/shipcloud')->load($_shipment->getId(),'shipment_id');
			?>
    <?php $i=0; foreach ($_shipment->getAllTracks() as $_item): $i++ ?>

        <tr <?php echo $i%2?'bgcolor="#eeeded"':'' ?>>

              	<td align="left" valign="top" style="padding:3px 9px"><?php echo $_item->getTitle() ?></td>



  			<?php $_url=$_shipment->getTrackUrl($_item->getTitle(),$_item->getNumber(), $zipcode) ?>

  			<?php $_carrier=$_item->getTitle();?>

        	<?php if($_carrier=="UPS"): ?>
                <?php $_mas="http://wwwapps.ups.com/WebTracking/track?HTMLVersion=5.0&loc=de_DE&Requester=UPSHome&WBPM_lid=homepage%2Fct1.html_pnl_trk&trackNums=".$_item->getNumber()."&track.x=Status+ermitteln"; ?>
            <?php elseif($_carrier=="DHL"): ?>
                <?php $_mas="http://nolp.dhl.de/nextt-online-public/set_identcodes.do?lang=de&idc=".$_item->getNumber();?>
            <?php elseif($_carrier=="HERMES"): ?>
                <?php $_mas="http://privatpaketservice.hlg.de/wps/portal/SENDUNGSSTATUS?auftragsNummerN=".$_item->getNumber();?>
            <?php elseif($_carrier=="DPD"): ?>
                <?php $_mas="http://extranet.dpd.de/cgi-bin/delistrack?pknr=".$_item->getNumber()."&typ=1&lang=de";?>
            <?php elseif($_carrier=="GLS"): ?>
                <?php $_mas="http://www.gls-group.eu/276-I-PORTAL-WEB/content/GLS/DE03/DE/5001.htm?txtAction=71000&txtQuery=".$_item->getNumber()."&x=0&y=0";?>
                       <?php endif; ?>
	    <?php if ($_url!=""): ?>

               	<td align="center" valign="top" style="padding:3px 9px"><a href="<?php echo $shipcloud->getTrackingurl() ?>" >Trackingnummer: <?php echo $_item->getNumber() ?></a></td>

  			 <?php else: ?>


            	<td align="center" valign="top" style="padding:3px 9px"><a href="<?php echo $shipcloud->getTrackingurl() ?>"><?php echo $_item->getNumber() ?></a></td>

  			 <?php endif; ?>

        </tr>

    <?php endforeach ?>

    </tbody>

</table>

<?php endif; ?>
