<?php if ($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
    <dt class="complete">
    <?php echo $this->__('Shipping Method') ?> <span class="changelink"><span class="separator">|</span> <a
            href="#shipping_method"
            onclick="checkout.changeSection('opc-shipping_method');
                    return false;"><?php echo $this->__('Change') ?></a></span>
    </dt>
    <dd class="complete">
        <?php if ($this->getShippingMethod()): ?>
            <?php echo $this->getShippingDescription() ?>

            <?php $_excl = $this->getShippingPriceExclTax(); ?>
            <?php $_incl = $this->getShippingPriceInclTax(); ?>
            <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                <?php echo $_incl; ?>
            <?php else: ?>
                <?php echo $_excl; ?>
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
            <?php endif; ?>

        <?php else: ?>
            <?php echo $this->__('Shipping method has not been selected yet');
            ?>
        <?php endif; ?>

        <div class="">

            <div>
                <?php
                $date_format = Mage::getStoreConfig('delivery/general/delivery_format');

                if ($date_format == '')
                    $date_format = 'd/M/Y';
                else
                    $date_format.=" ";
                if(Mage::getModel('core/cookie')->get('delivery_date')!='')
                {
                echo $this->__("Delivery Date :") . $currentDate = date($date_format, strtotime(Mage::getModel('core/cookie')->get('delivery_date')));
                }
                ?>
            </div>

            <div class="">   
                <?php 
                 if(Mage::getModel('core/cookie')->get('delivery_time')!='')
                 {
                echo $this->__('Delivery Time :') . Mage::getModel('core/cookie')->get('delivery_time'); 
                 }
                ?>
            </div>
            <div class="">
                <?php 
                 if(Mage::getModel('core/cookie')->get('delivery_comment')!='')
                 {
                echo $this->__('Delivery Comment :') . Mage::getModel('core/cookie')->get('delivery_comment');
                 }
                 ?>
            </div>
        </div>  
    </dd>
<?php else: ?>
    <dt>
    <?php echo $this->__('Shipping Method') ?>
    </dt>
<?php endif; ?>

