<a class="et_social_share" alt="<?php echo $this->__('Facebook Sign in') ?>" title="<?php echo $this->__('Facebook Sign in') ?>" onclick="open_windowLogin('<?php echo $this->getLoginUrl() ?>', 'Login Facebook')" href="javascript:void(0);">
    <i class="et_social_icon et_social_icon_facebook"></i> <div class="et_social_network_label"><div class="et_social_networkname"><?php echo $this->__('Facebook'); ?></div></div><span class="et_social_overlay"></span>
</a>
