<?php $suffix = strtolower($this->getNameInLayout()); ?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<?php 
    $storeId = Mage::app()->getStore()->getId();
    $summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId);
 ?>
<div class="widget-catalogsale-products-carousel products-grid" id="<?php echo $suffix ?>" >
	<div class="page-title category-title">
        <h1><?php echo $this->__('Special products') ?></h1>
    </div>
    <ul class="sale-carousel">
        <?php foreach ($_products->getItems() as $_product): ?>
        <?php $_productId = $_product->getId(); ?>
        <li class="swiper-slide item" itemscope itemtype="http://schema.org/product">
                    <div class="wrapper-hover">
                            <?php 
                                $summaryData->load($_product->getId());
                                if($summaryData['rating_summary']):
                                    echo $this->getReviewsSummaryHtml($_product, 'short');
                                endif; 
                            ?>        	
                    	<div class="product-image-container">
                            <?php $_product2 = Mage::getModel('catalog/product')->load($_product->getId()); ?>
                            <div class="label-product">             
                                <?php if($_product2->getData('new')){echo '<span class="new">'.$this->__('New').'</span>';  }?>
                                <?php if($_product2->getData('sale')){echo '<span class="sale">'.$this->__('Sale').'</span>';  }?>
                            </div>

                    		<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" itemprop="url">
                            <span class="line-t"></span>
                            <span class="line-r"></span>
                            <span class="line-b"></span>
                            <span class="line-l"></span>
                    		    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(228) ?>"  alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" itemprop="image" />
                    		</a>
                    	</div>
                    	<div class="product-info">
	                    	        <p class="product-name" itemprop="name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)" itemprop="name"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></p>
	        	            <?php echo $this->getPriceHtml($_product, true, '-widget-catalogsale-'.$suffix) ?>
                	     <div class="actions">
                    	            <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                    	                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn-stroke" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span></span></span></button>
                    	            <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                    	                <a title="<?php echo $this->__('View Details') ?>" class="button btn-details btn-stroke" href="<?php echo $_product->getProductUrl() ?>"><span><span></span></span></a>
                    	            <?php else: ?>
                    	                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    	            <?php endif; ?>
                    	        <ul class="add-to-links">
                    	            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    	                <li><a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" rel="tooltip" class="link-wishlist btn-stroke"></a></li>
                    	            <?php endif; ?>
                    	            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    	                <li><span class="separator">|</span> <a  title="<?php echo $this->__('Add to Compare') ?> " href="<?php echo $_compareUrl ?>" rel="tooltip" class="link-compare btn-stroke"></a></li>
                    	            <?php endif; ?>
                    	        </ul>
                    	    </div>
                    	</div>
                    </div>
        </li>
        <?php endforeach ?>
      </ul>
</div>
<?php endif; ?>

